A static library is created and devel@pi5-80:~/RPIPico2-Exp/examples $ find . -name *.a ./FreeRTOSBlink/build/libfreertos_config.a missing the flowing.
`vApplicationGetIdleTaskMemory', `vApplicationStackOverflowHook', and  `vApplicationGetTimerTaskMemory'
[100%] Linking CXX executable Blink.elf
/usr/lib/gcc/arm-none-eabi/12.2.1/../../../arm-none-eabi/bin/ld: CMakeFiles/Blink.dir/home/devel/pico2/freertos/FreeRTOS-Kernel/tasks.c.o: in function `prvCreateIdleTasks':
/home/devel/pico2/freertos/FreeRTOS-Kernel/tasks.c:3598: undefined reference to `vApplicationGetIdleTaskMemory'
/usr/lib/gcc/arm-none-eabi/12.2.1/../../../arm-none-eabi/bin/ld: CMakeFiles/Blink.dir/home/devel/pico2/freertos/FreeRTOS-Kernel/tasks.c.o: in function `vTaskSwitchContext':
/home/devel/pico2/freertos/FreeRTOS-Kernel/tasks.c:5104: undefined reference to `vApplicationStackOverflowHook'
/usr/lib/gcc/arm-none-eabi/12.2.1/../../../arm-none-eabi/bin/ld: CMakeFiles/Blink.dir/home/devel/pico2/freertos/FreeRTOS-Kernel/timers.c.o: in function `xTimerCreateTimerTask':
/home/devel/pico2/freertos/FreeRTOS-Kernel/timers.c:294: undefined reference to `vApplicationGetTimerTaskMemory'
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/Blink.dir/build.make:1579: src/Blink.elf] Error 1
make[1]: *** [CMakeFiles/Makefile2:2065: src/CMakeFiles/Blink.dir/all] Error 2
make: *** [Makefile:156: all] Error 2